name: Deployment

on:
  pull_request:
    branches:
      - main

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: non-production
    steps:
      - name: deploy
      - run: npm run deploy